### ISSUE TITLE
Detection of shape boundary dynamically ex. ( (business card) Rectangle , square and Circle) from the camera? #50

### ISSUE THREAD

**Issue by mahmooddagga** [priyankvex/Easy-Ocr-Scanner-Android#3]
I would like to get some help if possible . I'm trying to detect business card using my Android phone camera but I don't know where to start. so i can Extracting text from image using OCR and process it to read business card..

**Comment by priyankvex** [comment]
Yes you can do that for sure. This library can detect text from any image, so it will work for scanning business cards too.
